version: '3'
services:
  api:
    image: node:latest
    build: .
    network_mode: "host"
    environment:
      - PORT=8001
    volumes:
      - ./node_modules/:/opt/scraper/node_modules/
      - ./package.json:/opt/scraper/package.json
      - ./package-lock.json:/opt/scraper/package-lock.json
      - ./src/server.js:/opt/scraper/server.js
    ports:
      - "8001:8001"
    command: bash -c "cd /opt/scraper && npm install && npm run prod:server"

  database:
    image: mongo
    network_mode: "host"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=oskar123
    volumes:
      - ./conf/mongod.conf/:/etc/mongod.conf
      - ./database:/data/db
    ports:
      - "27017:27017"
    #command: bash -c "mongod --config /etc/mongod.conf"
    command: bash -c "mongod"
    #command: bash -c "tail -f /dev/null"