version: '3'
services:
  database:
    image: mongo:4.2-bionic
    container_name: database
    network_mode: "host"
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=oskar123
    volumes:
      - ./conf/mongod.conf/:/etc/mongod.conf
      - ./database:/data/db
    ports:
      - "27017:27017"
    #command: bash -c "mongod --config /etc/mongod.conf"
    command: bash -c "mongod"
    #command: bash -c "tail -f /dev/null"

  api:
    image: node:12
    container_name: api
    build: .
    network_mode: "host"
    environment:
      - PORT=8001
    volumes:
      #- ./node_modules/:/opt/scraper/node_modules/
      - ./package.json:/opt/scraper/package.json
      - ./package-lock.json:/opt/scraper/package-lock.json
      - ./src/api.js:/opt/scraper/api.js
    ports:
      - "8001:8001"
    command: bash -c "cd /opt/scraper && npm install && npm run prod:api"

  scraper:
    image: node:12
    container_name: scraper
    build: .
    network_mode: "host"
    #environment:
      #- PORT=8080
    volumes:
      - ./node_modules/:/opt/scraper/node_modules/
      - ./package.json:/opt/scraper/package.json
      - ./package-lock.json:/opt/scraper/package-lock.json
      - ./src/tvmatchen.js:/opt/scraper/tvmatchen.js
      - ./src/scraper.js:/opt/scraper/scraper.js
    #ports:
      #- "8001:8001"
    #command: bash -c "cd /opt/scraper && npm install && npm run prod:scraper"
    command: bash -c "tail -f /dev/null"