version: "3"

services:
  scraper:
    image: node:12
    container_name: scraper
    build: .
    network_mode: "host"
    environment:
      - NODE_ENV=production
    volumes:
      - ./node_modules/:/code/node_modules/
      - ./package.json:/code/package.json
      - ./package-lock.json:/code/package-lock.json
      - ./src/:/code/src/

    command: bash -c "cd /code && npm install && npm run dev:all"
